SecurityInnovation/PGPy

- docs/source/api/classes.rst.inc
This makes the distinction of the key and the value more clear.
> docs: Fixed typo in description of others

- pgpy/pgp.py
We only want to see if our key/subkey fingerprint is in some of the PKESKs, we don't care if it's in the signatures.
> Fix PGPKey.decrypt misusing message.issuers instead of encrypters.

- pgpy/types.py
- tests/test_03_armor.py
Adds a method to ease recognizing ASCII-armored data without fully parsing it, also adds test to check it works as intended.
> Add Armorable.is_armor(text) for detecting ASCII-armored data.

- pgpy/types.py
33ba06fd623fb7f19d6298f96d1f7c4b70db50e1 broke cleartext matching where the cleartext group was too greedy and matched the newline which shouldn't have been, see [travis](https://travis-ci.org/SecurityInnovation/PGPy/builds/245600522?utm_source=github_status&utm_medium=notification).
This PR fixes it, tests should pass although I am not sure my solution is the one. As that's a fairly complex regex, so now it might be broken in some other way? Anyway, tests should pass now.
> Fix armor regex being too greedy in cleartext matching.

- pgpy/constants.py
Just makes `PGPKey.parse` on a packet with pubkey algorithm `== 0x15` or `== 0x16` not fail. The first one is mentioned in RFC 4880 as reserved for X9.42 IETF-S/MIME. The other comes from https://tools.ietf.org/html/draft-koch-eddsa-for-openpgp-04. OpenSSL has EdDSA support however the `cryptography` package doesn't yet expose it, so we cannot use those keys but will not fail while encountering them. This should fix #177.
I think we should also not fail while importing stuff with constant values from `range(100,110)` as that's Experimental/Private range and I think at least allowing loading of those into their concrete Opaque types makes sense. Since now, even loading a message which contains a packet signed with `PubKeyAlgorithm == 100` will fail even when the message might have a …
> Don't raise when encountering an unknown key. Fixes #177 (partly).

- pgpy/packet/types.py
Packet tags are printed as decimal in the string and are also specified as decimal in the RFC4880, so dropping the `0x`.
> Fix wrong hexadecimal number prefix in Packet.__repr__.

- .travis.yml
This should fix Travis CI builds of forks. Which for some strange reason complain of running on `sudo: false` while the main repo runs on `sudo: required` magically! :smile:
> Fix Travis for forks.

- pgpy/types.py
- tests/test_02_packets.py
This adds support for partial length headers, currently only parsing them, not emitting them. With this PR PGPy can decode a partial length packet of indefinite length, however when outputing said packet back to bytes, it will be a packet with the usual 1 / 2 / 5 octet length, which means that packets with contents larger than `4,294,968,295 (0xFFFFFFFF)` octets will be output incorrectly.
However, currently PGPy will not even parse those packets, so I believe this is an improvement that covers a large part of the use-cases of PGP.
To get PGPy to output partial length packets for packets larger than the 5 octet length limit, significant changes to the `__bytearray__` logic will be required, as then, the packet header will need to insert bytes into the packet data itself. The current …
> Parse partial length headers correctly.

- pgpy/pgp.py
- tests/test_05_actions.py
This should fix #186 and #187 although this PR doesn't have tests(yet?). Also conflicts with #189. From [pgp.py#L814](https://github.com/SecurityInnovation/PGPy/blob/master/pgpy/pgp.py#L814) it seems that `__iter__` in `PGPMessage` should yield packets, however in it's current implementation it also yields `PGPSignature`.
```python
>>> list(smsg)
[<OnePassSignatureV3 [tag 0x04][v3] at 0x7fb99b877a20>, <LiteralData [tag 0x11] at 0x7fb99b877eb8>, <PGPSignature [BinaryDocument] object at 0x7fb99b88d828>]
````
#189 fixes that so iterating over all PGP* objects yields their packets at the cost of API change. See #189.
> Fix encrypt then sign.

- pgpy/types.py
- tests/test_99_regressions.py
Makes an empty string not dearmor like a valid ASCII-Armored blob.
> Fix PGPKey.from_blob('') not raising an exception. Fixes #199.

- pgpy/pgp.py
Removes a left out debug print in `PGPKey.__copy__`.
> Fix bogus print in PGPKey.__copy__.

- pgpy/pgp.py
- tests/test_04_PGP_objects.py
This PR allows one to load a PGPKey into a PGPKeyring via the load method. A copy of the PGPKey is added to the keyring.
> Add PGPKeyring.load() for PGPKey instance param.

- pgpy/pgp.py
This is indeed API breaking, however, the docstring clearly states what should be returned. Fixes #214.
> Fix sigsubj.by to be a pgpy.PGPKey instance. Fixes #214.

- pgpy/pgp.py
- tests/test_05_actions.py
Exposes the revocation signatures of the key(primary or sub), as they are filtered out of the `self_signatures` property.
```
...
OpenPGP users may transfer public keys.  The essential elements of a
transferable public key are as follows:
- One Public-Key packet
- Zero or more revocation signatures
...
```
> Add revocation_signatures property to PGPKey.

- docs/source/progress.rst
This adds WKD to the list of possible key discover protocols.
It also breaks down HKP support into more digestible chunks.
See also #229.
> Update status of network interactions protocols

- pgpy/pgp.py
I discovered this issue when trying to encrypt a string with a subkey. Stack trace:
```
File "sowbug-file.py", line xxx, in xxx
x = key.encrypt(pgpy.PGPMessage.new("hi"))
File "myenv/local/lib/python2.7/site-packages/pgpy/decorators.py", line 125, in _action
with self.usage(key, kwargs.get('user', None)) as _key:
File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
return self.gen.next()
File "myenv/local/lib/python2.7/site-packages/pgpy/decorators.py", line 92, in usage
if self.flags & set(_key._get_key_flags(user)):
File "myenv/local/lib/python2.7/site-packages/pgpy/pgp.py", line 1715, in _get_key_flags
return next(self.self_signatures).key_flags
File "myenv/local/lib/python2.7/site-packages/pgpy/pgp.py", line 1366, in self_signatures
else (self.parent.fingerprint.keyid, …
```
> pubkey method copies parent to newly generated public key

- pgpy/constants.py
- pgpy/pgp.py
- pgpy/symenc.py
- tests/test_99_regressions.py
- Add a `is_supported` property to symmetric ciphers and hash algorithms
in pgpy.constants.
At the moment, a hash algorithm is always supported.
A cipher algorithm is supported iff its .cipher is callable.
- When picking a preferred cipher from a preference list,
pick the first _supported_ one, instead of the first one.
- Check for `alg.is_supported` instead of `callable(alg.cipher)`
in pgpy.symenc._encrypt
---
This is a quickly sketched fix for #243.
There's a regression test that fails before it and passes after it, so I'm fairly sure it does fix the issue.
> #243 - Pick first _supported_ algorithm from preference list

- tests/test_05_actions.py
We were testing the wrong version of the curve string.  With this
change on python-cryptography 2.6.1 and openssl 1.1.1c, we drop from
26 xfailed to 14 xfailed tests.
> test the names of the curves against the stored list

- pgpy/pgp.py
- tests/test_99_regressions.py
Python strings don't use \ to escape either * or !.  So the
declarations here were adding to the list of warnings during the run
of the test suite.
Declaring them as raw (unescaped) strings keeps the warnings more quiet.
> Avoid warnings about bad escape characters

- pgpy/packet/fields.py
- setup.py
- tests/test_99_regressions.py
version 1.5 (released nearly 3 years ago, on 2016-08-26) introduced
sign() and verify() for all asymmetric algorithms.
Without this change, with modern versions of python-cryptography, we
see warnings like:
/usr/lib/python3/dist-packages/pgpy/packet/fields.py:1177: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
The version of python-cryptography in debian stretch (oldstable) is
1.7.1, for point of reference.
> move to python-cryptography v1.5

- pgpy/packet/packets.py
- pgpy/pgp.py
when creating an OpenPGP public key, or an OpenPGP signature packet, it can be handy to be able to set the creation time manually, rather than relying on the system clock.   These changes make that possible (but everything still works with the system clock if they are not set deliberately).
> Set creation times

- pgpy/constants.py
- pgpy/packet/fields.py
- tests/test_01_packetfields.py
Support for the String2Key [GNU extensions](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=doc/DETAILS;h=3046523da62c576cf6a765a8b0829876cfdc6b3b;hb=b0f0791e4ade845b2a0e2a94dbda4f3bf1ceb039#l1346).
1. Private key without the secret values, e.g., parent certify key kept on a separate offline machine.
2. Private key with secrete values stored on smartcard.
> Support for S2K GNU extensions

- pgpy/pgp.py
It may not be obvious for users of the API that we can get the list of
revoker keys for a given key from the (private) _signature list, so
add a convenient accessor.
This is not really useful right now because it will raise a
NotImplementedError if any such signature is found, but will become
actually quite useful once #198 lands.
This is part of the process to make revocation checks easier in #225.
> add convenience accessor for revocation keys

- pgpy/packet/fields.py
@rot42 noticed this first. it will affect the tests once we include native-formatted EC points in the test data.
> ensure that ECPoint copy works for native points

- pgpy/pgp.py
All modern OpenPGP clients support SHA256, and it is still believed to
be cryptographically strong.
In the event that PGPy encounters a situation where it cannot
determine the correct hash algorithm to use, it was previously
throwing surprising exceptions.
With these changes, it should fall back instead to SHA-256.
> fall back to SHA256 if no hashprefs are available

- pgpy/errors.py
- pgpy/packet/fields.py
This makes it easier to catch these specific types of errors if the
user wants to, and makes it clearer what is happening.
> Use dedicated exception class when ECPointFormat is wrong

- pgpy/constants.py
Without this change, the warning about IDEA is not properly rendered
in html, and ./setup.py build_sphinx itself produces a warning:
```
…/pgpy/constants.py:docstring of pgpy.constants.SymmetricKeyAlgorithm.IDEA:1: WARNING: Content block expected for the "warning" directive; none found.
…/pgpy/constants.py:docstring of pgpy.constants.SymmetricKeyAlgorithm.IDEA:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
```
> Fix sphinx warnings about IDEA documentation

- pgpy/pgp.py
This is done by setting 'crosssign' to False in the prefs parameter to
the sign function.
You probably don't want to use this feature! It is likely to make
OpenPGP certificates without cross-signatures that some other
implementations will reject.
> Permit skipping cross-signing unless strictly required

- pgpy/packet/subpackets/signature.py
The spec comes from here:
https://tools.ietf.org/html/draft-ietf-openpgp-rfc4880bis-07#section-5.2.3.28
Signed-off-by: Daniel Kahn Gillmor <dkg@fifthhorsemnan.net>
> IssuerFingerprint - include spec and update length for v5

- pgpy/pgp.py
The exportable flag is already implemented, but it is not documented
in the docstring.  This addresses that concern.
> PGPKey.certify: document exportable flag

- pgpy/packet/subpackets/signature.py
- tests/test_99_regressions.py
When the Signature Creation Time was supplied to the signing function,
we were ignoring the fact that it might have a different timezone than
UTC.  But the stored timestamp is supposed to always be in UTC, so it
should roundtrip correctly.
This includes a test to ensure that we don't end up with a regression.
Closes: #291
> When Signature Creation Time is supplied, use UTC

- pgpy/constants.py
- pgpy/packet/subpackets/signature.py
- pgpy/pgp.py
- tests/test_05_actions.py
Key Server Preferences (RFC 4880 §5.2.3.17) is a bitfield, more like
Key Flags (RFC 4880 §5.2.3.21) than Preferred Hash Algorithms (RFC
4880 §5.2.3.8).
The caller should be able to invoke this as a set when calling
PGPKey.certify().
This patch also improves documentation for PGPKey.certify() to
indicate how to pass in these flags.
> KeyServerPreferences is a bitfield, not a list

- pgpy/pgp.py
GnuPG has been including hashed Issuer Fingerprint subpackets by
default in signatures since 2016-10-08.  This subpacket makes it
possible to distinguish between a bad signature and a signature that
we happen to not have the issuer's key for.
We add it here for normal signature, certifications, and revocations,
unless the signer explicitly requests that it not be included.
> PGPKey._sign: include hashed Issuer Fingerprint subpacket by default.

- pgpy/pgp.py
While #262 made it possible to set creation times in some places, it
missed some others.
This makes the created= argument functional in all the contexts where
it could be useful.
> specify creation time more completely

- pgpy/pgp.py
This warning doesn't appear to be actionable, and is likely to only
encourage users of PGPy to do extra gymnastics before calling
decrypt().
Closes #297
> Drop noisy warning on decrypting with subkey

- pgpy/decorators.py
Similar to the concerns in #297, there are noisy warnings produced
when encrypting data to or signing data with a primary key, if a
subkey is ultimately what ends up being used:
```
./generate-test-vectors:279: UserWarning: Key F231550C4F47E38E does not have the required usage flag EncryptStorage, EncryptCommunications; using subkey 4766F6B9D5F21EB6
encmsg = alice_key.pubkey.encrypt(payloadmsg, cipher=cipher, sessionkey=sessionkey)
```
This change converts these warnings to debug information.
In #298, we just removed the noisy warnings on consuming data -- the
caller really has no choice in how to consume the data, so there's no
point in sending them alerts.  Either we can decrypt or verify with
the primary key or one of the subkeys, or we can't.
But in the situation where the caller is …
> Avoid noisy warnings when generating messages

- docs/source/api/constants.rst.inc
- pgpy/constants.py
- pgpy/packet/packets.py
- pgpy/packet/subpackets/signature.py
- pgpy/pgp.py
- tests/test_01_packetfields.py
See [1PA3PC specification](https://gitlab.com/openpgp-wg/rfc4880bis/merge_requests/20) for more details about first-party attestations.
This implementation makes it fairly straightforward for the user to create such an attestation, and to extract only the attested third-party certifications.
> Implement First-Party Attested Third-Party Certifications (1PA3PC)

- pgpy/packet/subpackets/signature.py
- pgpy/pgp.py
- tests/test_01_packetfields.py
See https://gitlab.com/openpgp-wg/rfc4880bis/merge_requests/19 and
https://0xacab.org/schleuder/schleuder/issues/158 for more details
about this subpacket.
The simplest way to use this when generating a message in PGPy is:
```
msg = PGPMessage.new('test message')
msg |= alice.sign(msg, intended_recipients=[bob])
msg = bob.encrypt(msg)
```
And it can be checked on Bob's side with:
```
cleartext = bob.decrypt(msg)
for sigvfy in alice.verify(cleartext).good_signatures:
if bob.fingerprint in sigvfy.signature.intended_recipients:
print("meant for Bob")
```
> handle and generate Intended Recipient subpackets

- pgpy/packet/packets.py
- pgpy/pgp.py
Over in #271, we discussed simplifying the lower-level UserID packet
object, and moving the <name,comment,email> splitting logic up into
the higher-layer PGPUID API.
This patch does that work, and also exposes an additional
PGPUID.userid property, which is the full UTF-8 string.
If this gets merged, it will obsolete #271.
> User IDs: simplify, treat as UTF-8 strings

- pgpy/constants.py
- tests/test_99_regressions.py
There were issues in trying to do CPU tuning (see #279 and #157 for
examples).
The simpler approach, given the capacity of modern hardware and the
antiquity of OpenPGP's S2K parameters, is just to always use the
maximum S2K settings.  This also saves us some CPU from running
calibration steps.
This commit also drops the test for #157 entirely, because that test
embeds assumptions about the way that calibration is done that are no
longer true.
If this is merged, we should close #279 without merging it.
> Max out S2K parameters

- docs/source/examples/keys.rst
The example code sets the key to expire in one year using timedelta(days=365), although the leading comment implies it will be set to ten years.
> Fix comment to align with example

- .travis.yml
- install_dependencies.linux.sh
- tests/conftest.py
- tests/test_05_actions.py
- tests/test_99_regressions.py
- tox.ini
- Fixed PEP8 test so it actually runs
- Updated `.travis.yml` to latest standard
- Made sure `install_dependencies.linux.sh` can be run without input
- Disabled OSX tests to reduce run time and visual noise
- Fixed import try/except so pypy test runs
- Updated `gpg` to 1.10.0 so pypy3 test runs
- Pin PyYAML to 5.2 only for Python 3.4
> Update and fix tests

- pgpy/pgp.py
PGPUID objects might lack a selfsig (e.g. weirdly structured input data).
In those situations, pgpy shouldn't crash, it should be able to carry on.
> fix crashes when a PGPUID object lacks a selfsig

- pgpy/pgp.py
- tests/test_99_regressions.py
According to RFC 4880, 'an implementation MAY dash-escape any line,
SHOULD dash-escape lines commencing "From" followed by a space [...]'.
Therefore it is necessary to unescape all lines starting with dash-space
sequences, and not just these that have a dash following this sequence.
Fixes #341
> Fix dash un-escaping to be applied unconditionally

- pgpy/constants.py
This PR adds private/experimental hash algorithm IDs so keys using these do not fail at importing
> Support keys with private/experimental hash algorithms

- docs/source/installation.rst
Let me know if I should change the wording or location. I explicitly put it above Fedora/RHEL because the sentence about `python3-dev` still applies here.
> Add alpine linux install instructions

- .github/workflows/tests.yml
- .travis.yml
- Brewfile
- install_dependencies.osx.sh
- tox.ini
- tox.sh
This PR moves us from Travis CI to GitHub Actions as our primary CI due to changes Travis has made to its open source support. We'll still have Travis run tests for now, but will primarily pay attention to GitHub.
> Use GitHub Actions as primary CI

- docs/source/examples/actions.rst
- docs/source/examples/keys.rst
- pgpy/decorators.py
- pgpy/pgp.py
- tests/test_05_actions.py
This works for this issue: [Option to override/ignore flags (like gpg)](https://github.com/SecurityInnovation/PGPy/issues/257)
You only need assign _require_usage_flags as False to you key before call encrypt function
```python
from pgpy import PGPKey
from pgpy import PGPMessage
key, _ = PGPKey.from_file('path/to/key_without_usage_flags.asc')
msg_pgp = PGPMessage.new(msg_to_encrypt)
key._require_usage_flags = False  # This allow ignore the validation
encrypted_phrase = key.encrypt(msg_pgp)
```
> Feature:: Support for keys without usage flags

- setup.cfg
A setup.cfg project metadata section is only ever parsed by setuptools, and thusly does not need to specify that it depends on having setuptools installed (it is already specified in the pyproject.toml)
Wheel is not required either, since it is only actually used by the pyproject.toml specified build backend, and wheel is already specified in the pyproject.toml
pyproject.toml build-requires is intended to specify the basic requirements for acquiring a usable instance of the build backend. These packages are dependencies of PEP 517.
setup_requires is intended only for additional project-specific packages needed in addition to the build backend. These packages are dependenciesof setuptools.setup()
Example difference: wheel is required in order to create a wheel, pyproject.toml specifies the …
> remove unneeded setup_requires which are already in pyproject.toml

- tests/conftest.py
distutils is going away in python 3.12.  LooseVersion() wasn't really
being used for anything particularly useful.  The strings that were
returned by the openssl backend for the cryptography module, or the
GPGME "engine" version were both just being replayed later as strings
anyway.
So, keep them in string form.  If future work needs to do things like
compare them, apparently packaging.version contains classes that might
be better-maintained going forward.
> tests: drop distutils

- setup.cfg
This PR will temporarily address the issue which makes `pip install PGPy` result in a broken environment.
Read more about this issue in:
- https://github.com/SecurityInnovation/PGPy/issues/408
- https://github.com/SecurityInnovation/PGPy/issues/402
----
If any of the following people are still alive (and have write-access to this repo), I would greatly appreciate you merging this PR and triggering a release of PGPy version 0.5.5:
- @J-M0
- @dkg
- @tzaffi 
- @cravgabo 
- @justinkb 
- @sharuzzaman
- @Gee19
- @mgorny
- @vollkorn1982
- @KOLANICH
- @tirkarthi
- @matt-wesley 
- @tydeu 
- @Commod0re
- @jonathancross
- @rot42
- @fuhrysteve
- @iburadempa
- @Wolf480pl
(Sorry for the mass ping, but I have no idea who is dead/alive)
> pin cryptography < 38.0.0 (fix pip install)

- tests/conftest.py
In commit 08a76fdda9fc2d5e04925a94dec17132ab0a899a, distutils was dropped. Before then, gpg_ver was a global mutable class instance, mutated inside a function and then used. After then, it's a global string that is... also modified inside a function and then used.
Strings cannot be modified inside functions like that. It shadows the variable in the local scope, which means the global variable is inaccessible now. In fact the global variable exists solely to be used inside this function, but now it cannot be.
So, because it can be bound inside the function, it *must* be, but only if python-gpg was installed did this actually occur. If not, we skipped the integration tests and then tried to log the version, assuming that the global default value of "unknown" was still bound, which is no …
> fix testsuite regression that immediately crashed without integration tests

- pgpy/types.py
They can occur e.g. in armor headers.
Fixes: #395
> Allow tabs in regex for ASCII validity check

- pgpy/_curves.py
#402 
Use `ec.EllipticCurve` as parent class instead of using the removed decorator `cryprography.utils.register_interface`.
Disclaimer: I'm just looking at what others did and what [this comment](https://github.com/SecurityInnovation/PGPy/issues/402#issuecomment-1239827481) says. I did not test this nor do I know what to do here.
> fix removed cryptography.utils.register_interface

- pgpy/pgp.py
- tests/test_99_regressions.py
As per RFC 4880 13.2, "Since TripleDES is the MUST-implement algorithm,
if it is not explicitly in the list, it is tacitly at the end."
Some keys in the wild do not have it explicitly in the list, so put it
there as a default.
Fixes #393
> Default to 3DES when preferred algorithms don't have any supporting algorithm

- pgpy/packet/fields.py
The OpenPGP specifications are ambiguous about the encoding of
passwords.
In practice, we expect most passphrases to be UTF-8-encoded, but if
the incoming passphrase is in fact a bytestring, we ought to be able
to handle it correctly.
The function signature for `PGPMessage.decrypt()` suggests that `passphrase` can be either `str` or `bytes`, but it chokes when passed a `bytes` object with a backtrace like so:
```
File "/usr/lib/python3/dist-packages/pgpy/pgp.py", line 1241, in decrypt
symalg, key = skesk.decrypt_sk(passphrase)
File "/usr/lib/python3/dist-packages/pgpy/packet/packets.py", line 586, in decrypt_sk
sk = self.s2k.derive_key(passphrase)
File "/usr/lib/python3/dist-packages/pgpy/packet/fields.py", line 1027, in …
```
> Accept passphrases as bytes

- tests/conftest.py
It should be in the moduke scope in order to allow it be imported by other modules in `tests` dir
> Fixed `gpg_ver` initialization in `conftest.py`.

- tox.ini
I'm seeing errors like this in the test-setup and unit-tests CI jobs:
> py: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'HOME ARCHFLAGS LDFLAGS CFLAGS INCLUDE LIB LD_LIBRARY_PATH PATH'
and:
> py39-setup: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'HOME ARCHFLAGS LDFLAGS CFLAGS INCLUDE LIB LD_LIBRARY_PATH PATH'
Despite the fact that [tox documentation](https://tox.wiki/en/3.1.2/config.html) says that "passenv" is "SPACE-SEPARATED-GLOBNAMES", the setup seems to think that "pass_env" (which is not "passenv", note the lack of underscore) is somehow bad.  Maybe putting each value on its own line will satisfy this check?
> Try to avoid tox test setup failures in unit-tests and test-setup CI jobs
